In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('darkgrid')
import nltk

In [2]:
df = pd.read_csv(r"C:\Users\anjal\Downloads\IMDB Dataset.csv\IMDB Dataset.csv")
df

review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [3]:
#Summary of the dataset
df.describe()

review sentiment
count                                               50000     50000
unique                                              49582         2
top     Loved today's show!!! It was a variety and not...  positive
freq                                                    5     25000

In [4]:
#sentiment count
df['sentiment'].value_counts()

positive    25000
negative    25000
Name: sentiment, dtype: int64

In [5]:
import pandas as pd


# Set the random seed for reproducibility
random_seed = 42
sample_size = 20000

# Randomly sample 20,000 rows from the original dataset
data = df.sample(n=sample_size, random_state=random_seed)

# Now 'sampled_df' contains 20,000 random samples from your original dataset


In [6]:
#split the dataset  
#train dataset
train_reviews=data.review[:14000]
train_sentiments=data.sentiment[:14000]
#test dataset
test_reviews=data.review[14000:]
test_sentiments=data.sentiment[14000:]
print(train_reviews.shape,train_sentiments.shape)
print(test_reviews.shape,test_sentiments.shape)

(14000,) (14000,)
(6000,) (6000,)


In [7]:
from nltk.tokenize.toktok import ToktokTokenizer
#Tokenization of text
tokenizer=ToktokTokenizer()
#Setting English stopwords
stopword_list=nltk.corpus.stopwords.words('english')

In [8]:
import re
#Removing the html strips
from bs4 import BeautifulSoup

def strip_html(text):
    soup = BeautifulSoup(text, "html.parser")
    return soup.get_text()

#Removing the square brackets
def remove_between_square_brackets(text):
    return re.sub('\[[^]]*\]', '', text)

#Removing the noisy text
def denoise_text(text):
    text = strip_html(text)
    text = remove_between_square_brackets(text)
    return text
#Apply function on review column
data['review']=data['review'].apply(denoise_text)

C:\ProgramData\Anaconda3\lib\site-packages\bs4\__init__.py:435: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  warnings.warn(


In [9]:
#Define function for removing special characters
def remove_special_characters(text, remove_digits=True):
    pattern=r'[^a-zA-z0-9\s]'
    text=re.sub(pattern,'',text)
    return text
#Apply function on review column
data['review']=data['review'].apply(remove_special_characters)

In [10]:
#Stemming the text
def simple_stemmer(text):
    ps=nltk.porter.PorterStemmer()
    text= ' '.join([ps.stem(word) for word in text.split()])
    return text
#Apply function on review column
data['review']=data['review'].apply(simple_stemmer)

In [11]:
from nltk.corpus import stopwords
#set stopwords to english
stop=set(stopwords.words('english'))
print(stop)

#removing the stopwords
def remove_stopwords(text, is_lower_case=False):
    tokens = tokenizer.tokenize(text)
    tokens = [token.strip() for token in tokens]
    if is_lower_case:
        filtered_tokens = [token for token in tokens if token not in stopword_list]
    else:
        filtered_tokens = [token for token in tokens if token.lower() not in stopword_list]
    filtered_text = ' '.join(filtered_tokens)    
    return filtered_text
#Apply function on review column
data['review']=data['review'].apply(remove_stopwords)

{'against', 'be', 's', 'had', 'did', 'if', 'ain', 'at', 'him', 'nor', 'an', 'weren', 'too', 'down', 'off', 'once', 'herself', "didn't", 'shan', 'such', 'ours', 'than', 'me', 'which', 've', 'who', 'her', 'itself', 'were', 'has', 'from', 'doesn', 'all', 'have', 'his', 'over', 'then', 'are', "won't", "you're", 'don', 'its', "wouldn't", "hadn't", 'and', 'haven', 'themselves', 'their', 'about', 'with', 'further', 'hadn', 'hasn', "mightn't", 'couldn', 'y', 'my', 'in', 'been', 'most', 'same', 'between', 'of', "hasn't", 'the', 'why', 'after', 'how', 'here', 'd', 'isn', 'not', 'these', 'is', "you'll", 'm', 'a', "should've", 'what', 'before', 'but', 'am', 'do', 'to', 'needn', 'into', "weren't", 'above', 'yourself', 'hers', 'by', 'when', "shan't", 'myself', "isn't", 'because', 'until', 'yourselves', "she's", 'other', 'up', 'just', 'can', 'wouldn', 'below', 'own', 'that', 'yours', 'on', "aren't", 'any', 'we', 'both', 'there', 'now', 'through', 'ma', 'some', 'shouldn', 'each', 'having', "you've", '

In [12]:
# normalized train reviews
norm_train_reviews = data.review[:14000]
first_review = norm_train_reviews.iloc[0]
print(first_review)


realli like thi summerslam due look arena curtain look overal wa interest reason anyway thi could one best summerslam ever wwf didnt lex luger main event yokozuna time wa ok huge fat man vs strong man im glad time chang wa terribl main event like everi match luger terribl match card razor ramon vs ted dibias steiner brother vs heavenli bodi shawn michael vs curt hene thi wa event shawn name hi big monster bodi guard diesel ir vs 123 kid bret hart first take doink take jerri lawler stuff hart lawler wa alway veri interest ludvig borga destroy marti jannetti undertak took giant gonzalez anoth terribl match smoke gunn tatanka took bam bam bigelow headshrink yokozuna defend world titl lex luger thi match wa bore ha terribl end howev deserv 810


In [13]:
#Normalized test reviews
norm_test_reviews=data.review[14000:]
norm_test_reviews[5005]

'almost made fool wa go start thi review say thi movi remind billi elliot look resum screenwrit lee hall onli find wa guy wrote billi elliot mr hall make fool bit cruel becaus lee ha someth aspir screenwrit britain dont ha hi foot door ha previous written success british movi award made money box offic doe next give audienc young jimmi spud live kitchen sink estat bulli school one love onli thing keep go ha aspir ballet dancer actual ha aspir angel consid hi household may well ballet dancer ha macho waster father think ballet dancer bunch poof hi granddad say ballet dancer tough ani man could meet rememb see bolshoi ballet yup ballet main talk point run british council estat day come think neither left wing polit seem sole preserv middl class gooder live nice big hous right away everyth thi set feel ridicul fals anoth major critic thi film ha clue tri appeal often criticis channel 4 broadcast movi total inappropri time land time forgot 6 exampl show thi 2 onc theyv got spot consid stor

In [14]:
from sklearn.feature_extraction.text import CountVectorizer
#Count vectorizer for bag of words
cv=CountVectorizer(min_df=0,max_df=1,binary=False,ngram_range=(1,3))
#transformed train reviews
cv_train_reviews=cv.fit_transform(norm_train_reviews)
#transformed test reviews
cv_test_reviews=cv.transform(norm_test_reviews)

print('BOW_cv_train:',cv_train_reviews.shape)
print('BOW_cv_test:',cv_test_reviews.shape)
#vocab=cv.get_feature_names()-toget feature names

BOW_cv_train: (14000, 2470308)
BOW_cv_test: (6000, 2470308)


In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer
#Tfidf vectorizer
tv=TfidfVectorizer(min_df=0,max_df=1,use_idf=True,ngram_range=(1,3))
#transformed train reviews
tv_train_reviews=tv.fit_transform(norm_train_reviews)
#transformed test reviews
tv_test_reviews=tv.transform(norm_test_reviews)
print('Tfidf_train:',tv_train_reviews.shape)
print('Tfidf_test:',tv_test_reviews.shape)

Tfidf_train: (14000, 2470308)
Tfidf_test: (6000, 2470308)


In [16]:
from sklearn.preprocessing import LabelBinarizer
#labeling the sentient data
lb=LabelBinarizer()
#transformed sentiment data
sentiment_data=lb.fit_transform(data['sentiment'])
print(sentiment_data.shape)

(20000, 1)


In [17]:
#Spliting the sentiment data
train_sentiments=sentiment_data[:14000]
test_sentiments=sentiment_data[14000:]
print(train_sentiments)
print(test_sentiments)

[[1]
 [1]
 [0]
 ...
 [0]
 [1]
 [0]]
[[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]


In [18]:
from sklearn.linear_model import LogisticRegression
#training the model
lr=LogisticRegression(penalty='l2',max_iter=500,C=1,random_state=42)
#Fitting the model for Bag of words
lr_bow=lr.fit(cv_train_reviews,train_sentiments)
print(lr_bow)
#Fitting the model for tfidf features
lr_tfidf=lr.fit(tv_train_reviews,train_sentiments)
print(lr_tfidf)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1, max_iter=500, random_state=42)


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1, max_iter=500, random_state=42)


In [19]:
#Predicting the model for bag of words
lr_bow_predict=lr.predict(cv_test_reviews)
print(lr_bow_predict)
##Predicting the model for tfidf features
lr_tfidf_predict=lr.predict(tv_test_reviews)
print(lr_tfidf_predict)

[0 1 1 ... 1 1 1]
[0 1 1 ... 1 1 1]


In [20]:
from sklearn.metrics import accuracy_score
#Accuracy score for bag of words
lr_bow_score=accuracy_score(test_sentiments,lr_bow_predict)
print("lr_bow_score :",lr_bow_score)
#Accuracy score for tfidf features
lr_tfidf_score=accuracy_score(test_sentiments,lr_tfidf_predict)
print("lr_tfidf_score :",lr_tfidf_score)

lr_bow_score : 0.7258333333333333
lr_tfidf_score : 0.7121666666666666


In [21]:
from sklearn.metrics import classification_report
#Classification report for bag of words 
lr_bow_report=classification_report(test_sentiments,lr_bow_predict,target_names=['Positive','Negative'])
print(lr_bow_report)

#Classification report for tfidf features
lr_tfidf_report=classification_report(test_sentiments,lr_tfidf_predict,target_names=['Positive','Negative'])
print(lr_tfidf_report)

              precision    recall  f1-score   support

    Positive       0.75      0.69      0.72      3043
    Negative       0.71      0.76      0.73      2957

    accuracy                           0.73      6000
   macro avg       0.73      0.73      0.73      6000
weighted avg       0.73      0.73      0.73      6000

              precision    recall  f1-score   support

    Positive       0.79      0.59      0.68      3043
    Negative       0.67      0.84      0.74      2957

    accuracy                           0.71      6000
   macro avg       0.73      0.71      0.71      6000
weighted avg       0.73      0.71      0.71      6000



In [22]:
from sklearn.metrics import confusion_matrix
#confusion matrix for bag of words
cm_bow=confusion_matrix(test_sentiments,lr_bow_predict,labels=[1,0])
print(cm_bow)
#confusion matrix for tfidf features
cm_tfidf=confusion_matrix(test_sentiments,lr_tfidf_predict,labels=[1,0])
print(cm_tfidf)

[[2246  711]
 [ 934 2109]]
[[2470  487]
 [1240 1803]]


In [23]:
from sklearn.linear_model import SGDClassifier
#training the linear svm
svm=SGDClassifier(loss='hinge',max_iter=500,random_state=42)
#fitting the svm for bag of words
svm_bow=svm.fit(cv_train_reviews,train_sentiments)
print(svm_bow)
#fitting the svm for tfidf features
svm_tfidf=svm.fit(tv_train_reviews,train_sentiments)
print(svm_tfidf)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SGDClassifier(max_iter=500, random_state=42)


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SGDClassifier(max_iter=500, random_state=42)


In [24]:
#Predicting the model for bag of words
svm_bow_predict=svm.predict(cv_test_reviews)
print(svm_bow_predict)
#Predicting the model for tfidf features
svm_tfidf_predict=svm.predict(tv_test_reviews)
print(svm_tfidf_predict)

[1 1 1 ... 1 1 1]
[1 1 1 ... 1 1 1]


In [25]:
#Accuracy score for bag of words
svm_bow_score=accuracy_score(test_sentiments,svm_bow_predict)
print("svm_bow_score :",svm_bow_score)
#Accuracy score for tfidf features
svm_tfidf_score=accuracy_score(test_sentiments,svm_tfidf_predict)
print("svm_tfidf_score :",svm_tfidf_score)

svm_bow_score : 0.618
svm_tfidf_score : 0.4975


In [26]:
#Classification report for bag of words 
svm_bow_report=classification_report(test_sentiments,svm_bow_predict,target_names=['Positive','Negative'])
print(svm_bow_report)
#Classification report for tfidf features
svm_tfidf_report=classification_report(test_sentiments,svm_tfidf_predict,target_names=['Positive','Negative'])
print(svm_tfidf_report)

              precision    recall  f1-score   support

    Positive       0.89      0.28      0.43      3043
    Negative       0.57      0.96      0.71      2957

    accuracy                           0.62      6000
   macro avg       0.73      0.62      0.57      6000
weighted avg       0.73      0.62      0.57      6000

              precision    recall  f1-score   support

    Positive       1.00      0.01      0.02      3043
    Negative       0.50      1.00      0.66      2957

    accuracy                           0.50      6000
   macro avg       0.75      0.50      0.34      6000
weighted avg       0.75      0.50      0.34      6000



In [27]:
#confusion matrix for bag of words
cm_bow=confusion_matrix(test_sentiments,svm_bow_predict,labels=[1,0])
print(cm_bow)
#confusion matrix for tfidf features
cm_tfidf=confusion_matrix(test_sentiments,svm_tfidf_predict,labels=[1,0])
print(cm_tfidf)

[[2848  109]
 [2183  860]]
[[2957    0]
 [3015   28]]


In [28]:
from sklearn.naive_bayes import MultinomialNB
#training the model
mnb=MultinomialNB()
#fitting the svm for bag of words
mnb_bow=mnb.fit(cv_train_reviews,train_sentiments)
print(mnb_bow)
#fitting the svm for tfidf features
mnb_tfidf=mnb.fit(tv_train_reviews,train_sentiments)
print(mnb_tfidf)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


MultinomialNB()
MultinomialNB()


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [29]:
#Predicting the model for bag of words
mnb_bow_predict=mnb.predict(cv_test_reviews)
print(mnb_bow_predict)
#Predicting the model for tfidf features
mnb_tfidf_predict=mnb.predict(tv_test_reviews)
print(mnb_tfidf_predict)

[0 1 1 ... 1 1 1]
[0 1 1 ... 1 1 1]


In [30]:
#Accuracy score for bag of words
mnb_bow_score=accuracy_score(test_sentiments,mnb_bow_predict)
print("mnb_bow_score :",mnb_bow_score)
#Accuracy score for tfidf features
mnb_tfidf_score=accuracy_score(test_sentiments,mnb_tfidf_predict)
print("mnb_tfidf_score :",mnb_tfidf_score)

mnb_bow_score : 0.7276666666666667
mnb_tfidf_score : 0.723


In [31]:
#Classification report for bag of words 
mnb_bow_report=classification_report(test_sentiments,mnb_bow_predict,target_names=['Positive','Negative'])
print(mnb_bow_report)
#Classification report for tfidf features
mnb_tfidf_report=classification_report(test_sentiments,mnb_tfidf_predict,target_names=['Positive','Negative'])
print(mnb_tfidf_report)

              precision    recall  f1-score   support

    Positive       0.74      0.72      0.73      3043
    Negative       0.72      0.73      0.73      2957

    accuracy                           0.73      6000
   macro avg       0.73      0.73      0.73      6000
weighted avg       0.73      0.73      0.73      6000

              precision    recall  f1-score   support

    Positive       0.75      0.68      0.71      3043
    Negative       0.70      0.77      0.73      2957

    accuracy                           0.72      6000
   macro avg       0.73      0.72      0.72      6000
weighted avg       0.73      0.72      0.72      6000



In [32]:
#confusion matrix for bag of words
cm_bow=confusion_matrix(test_sentiments,mnb_bow_predict,labels=[1,0])
print(cm_bow)
#confusion matrix for tfidf features
cm_tfidf=confusion_matrix(test_sentiments,mnb_tfidf_predict,labels=[1,0])
print(cm_tfidf)

[[2173  784]
 [ 850 2193]]
[[2279  678]
 [ 984 2059]]


In [33]:
from sklearn.neighbors import KNeighborsClassifier
# Training the model for K-Nearest Neighbors
knn = KNeighborsClassifier(n_neighbors=5)
# Fitting the model for Bag of Words
knn_bow = knn.fit(cv_train_reviews, train_sentiments)
print(knn_bow)
# Fitting the model for tfidf features
knn_tfidf = knn.fit(tv_train_reviews, train_sentiments)
print(knn_tfidf)

# Predicting the model for Bag of Words
knn_bow_predict = knn.predict(cv_test_reviews)
print(knn_bow_predict)
# Predicting the model for tfidf features
knn_tfidf_predict = knn.predict(tv_test_reviews)
print(knn_tfidf_predict)

# Accuracy score for Bag of Words
knn_bow_score = accuracy_score(test_sentiments, knn_bow_predict)
print("knn_bow_score :", knn_bow_score)
# Accuracy score for tfidf features
knn_tfidf_score = accuracy_score(test_sentiments, knn_tfidf_predict)
print("knn_tfidf_score :", knn_tfidf_score)

# Classification report for Bag of Words 
knn_bow_report = classification_report(test_sentiments, knn_bow_predict, target_names=['Positive', 'Negative'])
print(knn_bow_report)
# Classification report for tfidf features
knn_tfidf_report = classification_report(test_sentiments, knn_tfidf_predict, target_names=['Positive', 'Negative'])
print(knn_tfidf_report)

# Confusion matrix for Bag of Words
cm_bow = confusion_matrix(test_sentiments, knn_bow_predict, labels=[1, 0])
print(cm_bow)
# Confusion matrix for tfidf features
cm_tfidf = confusion_matrix(test_sentiments, knn_tfidf_predict, labels=[1, 0])
print(cm_tfidf)

KNeighborsClassifier()
KNeighborsClassifier()


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
knn_bow_score : 0.5158333333333334
knn_tfidf_score : 0.5066666666666667
              precision    recall  f1-score   support

    Positive       0.51      0.97      0.67      3043
    Negative       0.61      0.05      0.09      2957

    accuracy                           0.52      6000
   macro avg       0.56      0.51      0.38      6000
weighted avg       0.56      0.52      0.38      6000

              precision    recall  f1-score   support

    Positive       0.51      0.96      0.66      3043
    Negative       0.49      0.04      0.07      2957

    accuracy                           0.51      6000
   macro avg       0.50      0.50      0.37      6000
weighted avg       0.50      0.51      0.37      6000

[[ 142 2815]
 [  90 2953]]
[[ 119 2838]
 [ 122 2921]]


In [ ]:
import joblib
import nltk
from bs4 import BeautifulSoup
from nltk.tokenize.toktok import ToktokTokenizer
import re
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

# Assuming 'data' is your sampled dataset
sample_size = 20000
random_seed = 42
data = df.sample(n=sample_size, random_state=random_seed)

# Tokenization and preprocessing functions
tokenizer = ToktokTokenizer()

def preprocess_text(text):
    # Your preprocessing steps here
    # ...

    # Assuming 'text' is preprocessed
    return text

# Preprocess the entire dataset
data['review'] = data['review'].apply(preprocess_text)

# Split the data into training and testing sets
train_size = 14000
train_data = data.iloc[:train_size]
test_data = data.iloc[train_size:]

# Initialize and fit the TF-IDF vectorizer
tv = TfidfVectorizer(min_df=0, max_df=1, use_idf=True, ngram_range=(1, 3))
tv_train_reviews = tv.fit_transform(train_data['review'])
tv_test_reviews = tv.transform(test_data['review'])

# Save the fitted vectorizer for later use
joblib.dump(tv, 'tfidf_vectorizer.pkl')

# Train and save your model (replace this with your actual training code)
# Assuming you have a SentimentAnalysisModel class with fit_vectorizer and fit_model methods
# sentiment_model = SentimentAnalysisModel()
# sentiment_model.fit_vectorizer(tv_train_reviews)
# sentiment_model.fit_model(your_training_labels)
# joblib.dump(sentiment_model, 'your_model.pkl')

# Save the trained model
# joblib.dump(sentiment_model, 'your_model.pkl')

# In a different notebook or script, you can load the vectorizer and model like this:
# loaded_vectorizer = joblib.load('tfidf_vectorizer.pkl')
# loaded_model = joblib.load('your_model.pkl')


In [34]:
import joblib
import nltk
from bs4 import BeautifulSoup
from nltk.tokenize.toktok import ToktokTokenizer
import re
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

# Assuming 'data' is your sampled dataset
sample_size = 20000
random_seed = 42
data = df.sample(n=sample_size, random_state=random_seed)

# Tokenization and preprocessing functions
tokenizer = ToktokTokenizer()

def preprocess_text(text):
    # Your preprocessing steps here
    # ...

    # Assuming 'text' is preprocessed
    return text

# Preprocess the entire dataset
data['review'] = data['review'].apply(preprocess_text)

# Split the data into training and testing sets
train_size = 14000
train_data = data.iloc[:train_size]
test_data = data.iloc[train_size:]

# Initialize and fit the TF-IDF vectorizer
tv = TfidfVectorizer(min_df=0, max_df=1, use_idf=True, ngram_range=(1, 3))
tv_train_reviews = tv.fit_transform(train_data['review'])
tv_test_reviews = tv.transform(test_data['review'])

# Save the fitted vectorizer for later use
joblib.dump(tv, 'tfidf_vectorizer.pkl')

# Train and save your model (replace this with your actual training code)
# ...

# Save the trained model
joblib.dump(train_sentiments, 'your_model.pkl')

# In a different notebook or script, you can load the vectorizer and model like this:
# loaded_vectorizer = joblib.load('tfidf_vectorizer.pkl')
# loaded_model = joblib.load('your_model.pkl')


['your_model.pkl']